# Use postgres/example userEntity/password credentials
version: '3.1'

services:
  db:
    image: postgres
#    build: db/evaluation-db
    restart: always
    environment:
        POSTGRES_USER: evaluation-dev
        POSTGRES_PASSWORD: evaluation-dev
        POSTGRES_DB: evaluation
    ports:
      - 5432:5432
    volumes:
      - ./db/evaluation-db:/docker-entrypoint-initdb.d

