spring:
  application:
    name: Evaluation

  messages:
    basename: i18n/messages
    cache-seconds: -1
    encoding: UTF-8
    always-use-message-format: false

  jpa:
    generate-ddl: false

app:
    exampleVar: This is an example

---
spring:
  profiles: development

  datasource:
#    platform: postgres
#    url: jdbc:postgresql://localhost:5432/evaluation
#    username: evaluation-dev
#    password: evaluation-dev
#    driverClassName: org.postgresql.Driver
    url: "jdbc:h2:~/test"
    driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    generate-ddl: true

  thymeleaf:
      cache: false

server:
  port: 8190

---
spring:
  profiles: preproduction

  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/evaluation
    username: evaluation-pre
    password: evaluation-pre
    driverClassName: org.postgresql.Driver

  server:
    port: 8190





